### ISSUE TITLE
A small correction if cuda not available

### ISSUE THREAD

**Issue by onurbarut** [thuml/Autoformer#63]
Hi,

I'm training your model on CPU, and while executing line 173 of exp_main.py

`            vali_loss = self.vali(vali_data, vali_loader, criterion)
`
in line 60 of AutoCorrelation.py it gives a cuda error while validating after training an epoch:

`            init_index = torch.arange(length).unsqueeze(0).unsqueeze(0).unsqueeze(0).repeat(batch, head, channel, 1).cuda()
`

Simply because of no cuda check.

Suggesting to add:

```
        # index init
        if torch.cuda.is_available():
            init_index = torch.arange(length).unsqueeze(0).unsqueeze(0).unsqueeze(0).repeat(batch, head, channel, 1).cuda()
        else:
            init_index = torch.arange(length).unsqueeze(0).unsqueeze(0).unsqueeze(0).repeat(batch, head, channel, 1)   
        
```
in methods `time_delay_agg_inference` and `time_delay_agg_full`

**Comment by Zero-coder** [comment]
good job.

**Comment by wuhaixu2016** [comment]
Hi, this problem is fixed in https://github.com/thuml/Autoformer/commit/a0a3862759dbedcdd158142f6748d7657b08a156
